app.js
Lovership offers were kept in memory if the player updated her lovership in one way or another, leading to various bugs, that should fix it.
=> fix : persistent Lovership offers

app.js
This is linked to the club PR [#919](https://github.com/Ben987/Bondage-College/pull/919)
This relaxes the restriction of chat room admins targeting themselves with admin actions, allowing the Swap, Move Left and Move Right cases.
=> Admin Actions on Self

app.js
Lover will only update Lovership if name starts with "NPC-"
part of the fix for breaking with "clingy" private lovers
=> Lovers fix - clingy Private Lovers

app.js
Small bugfix in title sync.
When a player updates her title it gets saved in the DB but not in the online player list causing other players to see an outdated title in chat rooms.
=> Set title in online account list when updating title.

app.js
See the related client-side PR for the description.
This change is compatible with current version. No side effects should be seen.
Since the indentation changed and makes the diff look like a lot has changed and I know changing the server is a touchy subject, let me point out what lines I've added/modified here:
Here is where we acknowledge it and make it default to existing behavior. (Must be a bool)
```
var FullRooms = false;
if ((data.FullRooms != null) && (typeof data.FullRooms === "boolean")) FullRooms = data.FullRooms;
```
Here is the existing if statement modified to take it into account. (TRUE if show full rooms is true or if room is not full).
At this stage we know FullRooms is a boolean.
`if ((ChatRoom[C] != null) && ((FullRooms) || (ChatRoom[C].Account.length < …
=> Room search changes

web.config
Changes the order of rewrite rules in case the socket.io requests are being caught by the DynamicContent rule.
=> Re-orders rewrite rules

app.js
**This PR goes with [#1336](https://github.com/Ben987/Bondage-College/pull/1336)**
Allow the Active pose data to be an array.
This will no conflict with the live version, and will work with beta. Note that non-beta users will just see characters standing when the active pose is an array, but it does not create any bugs or crashes
=> Support array in active poses

app.js
Does not allow regular beeps to non-friends; leash beeps are silent and do not appear on the target player's screen
=> Enable leash beeps to non-friends

app.js
As a result of recent account purges, some players have been left with lovers whose accounts no longer exist. It is currently not possible to break with those lovers properly, as the player's database account update only currently happens if their lover's account can be found. This Fixes that so that a player's account is now updated even if their lover cannot be found in the database.
=> Bugfix: Allows players to break with non-existent lovers

app.js
Implements limiting connections based on IP address. If there are too many connections from one address, new ones are closed during connection.
IP limit is set to generous 64 to account for possibility of multiple people connecting from same IP (for example when using VPNs or other shared networks), across multiple tabs, while still preventing the problematic amount of connections.
When limit is reached, new connection is sent `"ForceDisconnect"`, `"ErrorRateLimited"` message before disconnecting the client. This is not visible on client and on current one will look like if the client is still trying to connect. This is fixed in client PR.
**Also prints IP that overstepped the connection limit to console**
Also changes, what events are reacted to before login and prevents handling …
=> Feature: IP connection limiting

app.js
Removes overwrite of the socket `id`, using already existing id in its place.
This will eliminate huge memory leak and has potential to fix some other obscure issues too, because socket.io relies on the id not changing internally.
I've tested this change a lot and together with @elliesec we looked through the server and client code and don't see any place where this could cause an issue.
=> Fix: Use socket's internal id instead of overwriting it

app.js
Finally found the source of `AccountError` problems that started happening recently.
The problem was, that during removal of duplicated account two different accounts were accidentally getting removed.
Bug reproduced reliably without the fix and the fix has been tested.
=> Fix: ErrorDuplicatedLogin removing two accounts

app.js, package-lock.json, package.json
Migrates server to socket.io version 3, while keeping it compatible with current client.
I tested everything locally with current client and didn't find any problems.
What might be problem is, if `ORIGINS` was set in environment to something else than `DefaultOrigins`.
I also didn't test new origin values, as I can't do so without access to bondageprojects.com website.
Reason for upgrade - measured times to send/receive 10000 chat messages:
v2: 19208ms (And sockets started to time out)
v3: 1318ms, no slowdown
=> Migration to socketio.io v3

app.js, package.json
Obsoletes/Includes: #77 
Optional client PR: [Client#2259](https://github.com/Ben987/Bondage-College/pull/2259)
Queues the logins, making sure only one is being processed at the same time and waits 50ms between them.
In practice this means 2-4 logins per second ( So ~3 minutes for everyone to log back after server restart in bussist times, which is a lot better than the server stumbling for 5-15 minutes )
This makes sure the server doesn't overload when many people try to login - eg right after server restart.
I did a lot of testing and didn't find any issues.
(testing included valid logins, invalid username, invalid password, disconnect before login is complete, small and large (400) number of logins at once)
=> Feature: Login queue

app.js, package.json
Uses socket.io "rooms" feature to send same message to mutiple clients, while only having to encode it once, providing large benefit for performance.
There is no change in behaviour and this change is only internal on server - no client change is required
Tested thoroughly with Sekkmer on private server; the test shown:
Around 21% improvement for chatroom messages
More than 100% improvement for character update messages
=> Socket.io rooms

app.js
Even though this PR includes all the functions introduced in #76, it does not enable them for usage yet. For this purpose, seperate pull requests will be opened. This is to make testing the individual functions easier as requested by @Ben987.
The same has been done with the related Client PR [#2253](https://github.com/Ben987/Bondage-College/pull/2253), which got split as described in [#2272](https://github.com/Ben987/Bondage-College/pull/2272).
**As this is the major part of the split of #76 in smaller PRs, i'll duplicate it's description here to make it easier to keep an overview over the total functionality**
> **This is the related server PR to Client PR [#2253](https://github.com/Ben987/Bondage-College/pull/2253)**
> 
> As in the client PR description mentioned, this Splits the …
=> ChatRoomSync-Split: Replacement functions only

app.js
This PR enables the use of function `ChatRoomSyncMemberLeave` added by PR #79 on which it depends. It is required by Client PR [#2275](https://github.com/Ben987/Bondage-College/pull/2275).
=> ChatRoomSync-Split: Enable ChatRoomSyncMemberLeave

app.js
~~Changes `ChatRoomSyncGetCharSharedData` to always send full whitelist and blacklist.~~
Changes `ChatRoomSyncMemberJoin` to add newly joining player to other's *lists, if they should be there
Previously there was a change to only send whitelist for players in room as it was sent everytime anyone joined or entered.
With Tessa's change, it will only be sent when players joins or to joining player. This has two effects:
- Lot less data is sent, so there is no need to save on the whitelist as it only is sent once
- WhiteList of player already in room isn't updated when different player on whitelist joins room, this was causing a bug.
Reproduction steps for the bug (all players in room must be on new version):
Players A and B are in room - player A has player C whitelisted, but this currently …
=> Fix: Send WhiteList&BlackList updates on join

app.js
Adapted the beta compatibility code for R67 to prepare the base for merging the missing ChatRoomSync replacement transactions.
Also Removed the beta compatibility code for the already merged transactions since it is no longer necessary after R67 goes live.
=> ChatRoomSync-Split: Beta compatibility code adaption for R67

app.js
This PR enables the use of function `ChatRoomSyncReorderPlayers` added by PR #79 on which it depends. It is required by Client PR [#2279](https://github.com/Ben987/Bondage-College/pull/2279).
=> ChatRoomSync-Split: Enable ChatRoomSyncReorderPlayers

app.js
This PR enables the use of function `ChatRoomSyncMovePlayer` added by PR #79 on which it depends. It is required by Client PR [#2278](https://github.com/Ben987/Bondage-College/pull/2278).
**Edit:**
`ChatRoomSyncMovePlayer` has been replaced with `ChatRoomSyncReorderPlayers`. This now relates on client PR [2279](https://github.com/Ben987/Bondage-College/pull/2279)
=> ChatRoomSync-Split: Enable ChatRoomSyncMovePlayer

app.js
This PR enables the use of function `ChatRoomSyncSwapPlayers` added by PR #79 on which it depends. It is required by Client PR [#2277](https://github.com/Ben987/Bondage-College/pull/2277).
**Edit:**
`ChatRoomSyncSwapPlayers` has been replaced with `ChatRoomSyncReorderPlayers`. This now relates on client PR [2279](https://github.com/Ben987/Bondage-College/pull/2279)
=> ChatRoomSync-Split: Enable ChatRoomSyncSwapPlayers

app.js
This PR enables the use of function `ChatRoomSyncRoomProperties` added by PR #79 on which it depends. It is required by Client PR [#2276](https://github.com/Ben987/Bondage-College/pull/2276).
=> ChatRoomSync-Split: Enable ChatRoomSyncRoomProperties

app.js
~~**Depends on and includes #54**~~
~~*The reason for this dependency is, that the types tremendously help during development and safeguard against possible errors.*~~
- Rewrites `AccountOwnership` to be more readable and stable.
- Adds new targeted Action `Release`, enabling owners to release submissive from the bond.
Edit: Removed dependency
=> Feature: Release submissive from ownership

app.js
This PR removes the temporary code that was required for backwards compatibility with non-beta clients when the ChatRoomSync split was tested. It serves no purpose anymore and should be deleted to keep the code clean.
=> Removed backwards compatibilty code of ChatRoomSync-Split change for non-beta clients during beta

app.js
Sends an character sync when any shared info is updated using `AccountUpdate` to prevent info desync.
=> Fix: Sync character when shared info is updated

app.js
- fixed a bug where lovers were sent to the client with a submissive label, which would in turn be interpreted incorrectly if you broke up with the person.
This properly labels the player as a lover, and not a submissive when sending it out, which will stop new cases of this bug from occurring. (The client will correct those over time when opening the friendlist)
=> Fix friendlist friend type

app.js
(note that the pr looks bigger than it actually is because I moved the `Acc == null` check to the beginning, the changes are small and consist just of the two lines to validate the data.Ban/data.Ban and using those values in the created room object)
- added support for including a ban/admin list when creating a room to reduce the amount of events required to get a room going
If this gets merged (or if you confirm it can be merged), 
Ill be able to go ahead with the planned refactor of autoban and room recreation (to remove the unnecessary room updates)
It will also allow us to add an input to list admins/banned people right from the start when we want to create a room
This does not have any compatibility issues with any version of the club
=> Optional admin/ban list on room creation

app.js
- made it so the server only triggers a chatroom leave if you are not currently in the room you are trying to join
This prevents spam from various things that can cause you to try to join the same room (scripts, console, leash), the most common being that if you are lagging or clicking fast, you might click on a room several time and get re-added to a room many times back to back which spams chat with join/leave messages
=> fix double join bugs

app.js
- swapped `pingInterval` from 25s to 50s and `pingTimeout` from 20s to 30s (for the discussed reasons, Im appending the conversation so others can see)
If we try something else during beta 2, I'm curious to see the difference between this and 40s for each
> There are two important config values, pingInterval and pingTimeout right now they are set to 25s and 20s respectively. This means every 25s the server pings and expects a pong within 20 seconds. If we increase both values to around  50s and 30s, it would allow for a longer "grace period" which would likely reduce DC's by a lot since clients have 10 more seconds to respond to a ping. It would also reduce server load since there would be less ping/pong requests happening. The only "downside" is that the time to detect a proper DC is a …
=> DC mitigation - Attempt 1

app.js
The "space" in a chatroom search (e.g. "" for female-only, "X" for mixed", "M" for male-only), can now be passed as an array of values in addition to a single string. This allows the results to included a few spaces instead of a single one. The Space will be included in the room data so the client knows which is which.
This is for an upcoming change to allow multiple gender spaces be appear on the same room list screen.
This is compatible with the old/current client which sends a single space in the query.
=> Search for multiple chat spaces

app.js
That makes it easier for the client; instead of having to guess what space they're in from the lobby they entered, just give them the real data.
Right now the client won't use it, but that gives an opportunity to cleanup the relogging, so it's likely I'll file a refactor PR on it later.
=> Send the room Space back to the client

app.js
This closes the hole allowing someone to either self-own or self-love, that has been known for a while and which people still seem to use. The server now ignores such messages, closing the loophole.
Additionally, there was a bug that would cause a second lover to be deleted in case you wanted to break up of your own lovership, as the removal would happen twice (once with us as the target, and the second time with us as the source). As the index we calculated for ourselves before running the "target removal" wasn't updated, when our own removal would happen this would remove another entry from the list. As that spurious removal was completely unexpected, that would also create an inconsistency, as the target didn't have us removed from their list, leading to a half-broken relationship. …
=> Fix a couple bugs with lovers and owners

app.js
This is a relaxation of the validation rules for the chatroom `Limit` property, since I've set the TS type for them to be numeric (which is more correct), so that an integer between 2 and 10 included would also be considered valid.
Otherwise someone is gonna trip up on it at some point and wonder 😅.
=> Accept either a numeric base-10 string or a number as a room limit

app.js
Follow up to #177, as you can pass odd objects and cause an exception to be thrown.
=> As parseInt can indeed raise in some cases, write a safe wrapper for it

Messages.d.ts, app.js
After studying the behavior of the old client against the new server a little bit, it turns out there's a possibility of something odd happening with the relog code (not that it wouldn't also happen naturally). So, in order to impact the client as less as possible when the server gets the updated code, this puts the new show-locked-rooms behavior under an option. The old client will never set it, meaning it'll get the usual list, while the issue with the relog code can be fixed once it gets enabled, then the option can be removed and ignored, making it the default behavior.
=> Only show locked rooms if the client asks for them

Messages.d.ts, app.js
The old code did a reverse search through the chat to build the search results. Replace that code by making a copy of the ChatRoom array and reversing it.
=> Reverse the order in which search results are sent to the client

app.js
Following [this](https://discord.com/channels/554377975714414605/1315008403722080298/1316561686744010752) discussion on Discord, it became clear that the functionality of whitelist bypassing private had unintended effects. This is a quick patch to revert that change, only allowing admins to bypass private rooms, and hence giving users an option to allow users to enter/leave a locked room, but not find it in the search.
The corresponding [client!5328](https://gitgud.io/BondageProjects/Bondage-College/-/merge_requests/5328) updates the UI to reflect this change.
This is a ***temporary quick fix*** (which should be implemented ***before the R111 release***) and in the long term, #212 should be used instead.
=> revert: disallow whitelist from bypassing private

Messages.d.ts, app.js
These are the corresponding server changes necessary for the Visibility/Access list implementation, which [client!5237](https://gitgud.io/BondageProjects/Bondage-College/-/merge_requests/5327) is reliant upon. For more details on this change, see the linked MR.
As this directly pertains to the server code, I will additionally be going over the impact and current backward-compatability methodology of this change:
- The `Private` and `Locked` properties are intended to be sunset following the full release of the client functionality
- As there will be a transition period in which some clients are running the Visiblity/Access implementation and some are running the old Private/Locked implementation, there is a set of backward-compatability patches present in the code that should be removed …
=> feat(rooms): replace private/locked with granular visibility/access lists

app.js
Fix for a bug that's caused `ChatRoomSpace` to not be sent in the right circumstances (sending when they _don't_ have permissions to view the room rather than when they _do_). Thankfully, this only affects the space itself, which isn't an especially sensitive bit of data; I've double-checked and confirmed that it doesn't occur anywhere else.
=> fix(friends-list): correct erroneous [non-]transmission of ChatRoomSpace

app.js
Revealed if the player can join a room through a new `CanJoin` property of returned room data objects. It is `true` if they can join and `false` if they cannot join. If the property somehow ends up `undefined`, the code on the client side will default to a lock icon, and no error will happen.
Coincides with a client side merge request: https://gitgud.io/BondageProjects/Bondage-College/-/merge_requests/5421
=> Added the CanJoin property to chat rooms when they are loaded.
