Ben987/Bondage-Club-Server

app.js

Added actions to Move a character inside a room to the left or right by admins.

Added MoveLeft and MoveRight to RoomAdmin Actions

---

app.js

server side change for #395 Item Permission System

item permission

---

app.js

for https://github.com/Ben987/Bondage-College/pull/443

add player Description property

---

app.js

Ability for admin to lock a room and change it to private
Chat UI redesign to follow

Room lock private

---

app.js

Server will receive/send a dictionary for actions to translate them correctly later per client basis.
to fully be working, must be accepted with Client Pull Request [#536](https://github.com/Ben987/Bondage-College/pull/536)

Dictionary for translation of actions

---

app.js

Goes with client side PR #551
same as before, but without the white space cleanup

added chatroom space to the beep object

---

app.js

requires https://github.com/Ben987/Bondage-College/pull/578

ServerMove functionality in ChatRoomAdmin

---

.gitignore
app.js

based on the work of EveFerox
requires client PR [#618 ](https://github.com/Ben987/Bondage-College/pull/618)to be usable
more details there
updated .gitignore with jetbrains folder

Lovers feature

---

app.js

advancing in a lovership now correctly updates both players, without needing to relog

fix : advancing in a lovership now correctly updates both players

---

app.js

add ChatRoomSyncSingle to update a single character in the room
requires https://github.com/Ben987/Bondage-College/pull/594

ChatRoomSyncSingle 

---

app.js

needed for PR [#803](https://github.com/Ben987/Bondage-College/pull/803)

Limited items permission

---

app.js

Required for Client PR #[834](https://github.com/Ben987/Bondage-College/pull/834)
Complete description of the feature there

Multiple lovers

---

app.js

- correctly copies the lovership in the AccountUpdateLovership function
- fixed some crashes when breaking up with old data Lovership data

Multiple Lovers : more fixes

---

app.js

fixed incorrect check for couples with 4 lovers both that were unable to begin dating

lovers fix : incorrect check

---

app.js

This disables the initial long polling call that seems to be triggering the 404

Azure tests

---

app.js
web.config

Adds a `web.config` rule that should rewrite requests to socket.io to app.js.

Adds a rewrite rule for socket.io requests

---

web.config

the goal of this one is to just not interfere with socket.io routes and let them through

Test azure 2

---

web.config

Reverts Ben987/Bondage-Club-Server#48

Revert "Test azure 2"

---

app.js

This adds an object for online settings that need to be synced, they are separate from the rest.
Required for a client side PR[#1399]( https://github.com/Ben987/Bondage-College/pull/1399/files)

Share online settings

---

app.js

This allows the client to send a "BeepType" parameter in a beep, which will allow the client to leverage the existing code for beeps to send other types of messages to players, such as a "leash" beeptype to pull a user to the beeping member's room without actually showing a "beep" UI element to the leashed player

Added BeepType data to the beep function

---

app.js

**Requires [Bondage-College#2137](https://github.com/Ben987/Bondage-College/pull/2137)**
To be current version, otherwise there would be issues with players not having correctly updated whitelist, disallowing access to limited items in some cases
The patch should be fully deployed to stable version before this!
*Supports [Bondage-College#2138](https://github.com/Ben987/Bondage-College/pull/2138)*
- Explicitly enables compression on socket.io
- Enables improvements for new items saving format
- Filters sent whitelist based on players present in room

Improvement: Item save format

---

app.js

Sends beep's `Message` property, allowing sending of message with beeps.

Feature: Send messages with beeps

---

app.js
newrelic.js

Reverts Ben987/Bondage-Club-Server#72

Revert "Improve newrelic metrics"

---

app.js

This PR enables the use of function `ChatRoomSyncMemberJoin` added by PR #79 on which it depends. It is required by Client PR [#2274](https://github.com/Ben987/Bondage-College/pull/2274).

ChatRoomSync-Split: Enable ChatRoomSyncMemberJoin

---

app.js

This PR enables the use of function `ChatRoomSyncCharacter` added by PR #79 on which it depends. It is required by Client PR [#2273](https://github.com/Ben987/Bondage-College/pull/2273).

ChatRoomSync-Split: Enable ChatRoomSyncCharacter

---

app.js

- adds the required server-side changes to support the new favorite list. [#2619](https://github.com/Ben987/Bondage-College/pull/2619)

Inventory favorites

---

app.js

see https://github.com/Ben987/Bondage-College/pull/2893

Improvement: secret beeps

---

app.js

will conflict with #99, but the conflict is simple so Ill resolve it when needed.
- added a label to display that a room is private when the name is shown to lovers/owners for clarity

add private label to revealed rooms

---

.gitignore
app.js

This PR accompanies, and should be merged with or _after_ Ben987/Bondage-College#2920. It removes the `ServerMessages` from the server, as these have now been shifted onto the client. I also added the JetBrains-specific `.idea` directory to the `.gitignore` for JetBrains IDE users.

Feature: Improved console warnings

---

app.js

for..of changes: AccountRemove

---

app.js

for..of changes: ChatRoomAdmin

---

app.js

performance fix: break loop when target found

---

app.js

fix: keep idx in array when current entry removed

---

app.js

for..of changes: AccountLoginProcess

---

app.js

for..of changes: AccountGet

---

app.js

for..of changes: ChatRoomCreate

---

app.js

for..of changes: ChatRoomRemove

---

app.js

for..of changes: AccountUpdate

---

app.js

for..of changes: AccountQuery

---

app.js

for..of changes: AccountBeep

---

app.js

for..of changes: ChatRoomSearch

---

app.js

for..of changes: ChatRoomJoin

---

app.js

for..of changes: ChatRoomMessage

---

app.js

for..of changes: ChatRoomSyncToMember

---

app.js

for..of changes: ChatRoomSyncReorderPlayers

---

app.js

for..of changes: ChatRoomCharacterUpdate

---

app.js

for..of changes: ChatRoomCharacterItemUpdate

---

app.js

for..of changes: ChatRoomDominantValue

---

app.js

for..of changes: ChatRoomGetAllowItem

---

app.js

for..of changes: ChatRoomAllowItem

---

app.js

Proposed limits of 2 new connections per IP per second and 50 messages (of any kind) per second per connection.

add rate limiting

---

app.js

Reverts Ben987/Bondage-Club-Server#147

Revert "add rate limiting"

---

app.js

Reverts Ben987/Bondage-Club-Server#148

Revert "Revert "add rate limiting""

---

app.js

for..of changes: AccountLovership

---

app.js

Updates the chatroom character swap action dictionary to ensure character substitution doesn't get the two target characters mixed up.

Fixes chatroom character swap chat dictionary

---

app.js

This fixes a scoping issue with the `L` variables being both `var`s and used as a loop index *and* the final lovership info.

Fix a pair of simple const/let scoping problems

---

Messages.d.ts
MessagesPatch.d.ts
app.js
jsconfig.json
package-lock.json
package.json
typedef.d.ts

This copies over the `Messages.d.ts` file from the client so that the server also benefits from the TS goodness.

Bring in the TS types from the client

---

app.js

Allows players to call name almost like they want.
Allows any ***printable*** [ASCII character](https://www.ascii-code.com/).

Room name expansion

---

app.js
typedef.d.ts

This goes after #178. I'll be marking the only code change in in explicitly, since the diff will show the rest of that base branch.

Fix TS error in AccountCreate

---

app.js

Fix TS error in chatroom pose update

---

Messages.d.ts
app.js

Fix TS error in chatroom get data

---

.editorconfig

No functional change, this is just a missing entry in the .editorconfig file

Indent ts files the same as js files

---

app.js

This centralize all of the regex the server uses to validate data in a central location instead of having them duplicated, and syncs their value with what the client does.
Note that a lot of the length checks have also been moved in them to simplify the validation conditions.

Synchronize validation regex with the client

---

Messages.d.ts
app.js

These are the corresponding server changes necessary for the Room Whitelist implementation (interdependent). See the client counterpart for more information: [client!5281](https://gitgud.io/BondageProjects/Bondage-College/-/merge_requests/5281).

Room Whitelist Server Changes
